responseDirectory: /tmp/dlab
warmupPollTimeout: 5s
keyLoaderPollTimeout: 2m

server:
  applicationConnectors:
    - type: http
      port: 8084
  adminConnectors:
    - type: http
      port: 8085

logging:
  level: INFO
  loggers:
    com.epam: DEBUG
  appenders:
    - type: console