keyDirectory: /home/ubuntu/keys
responseDirectory: /tmp/dlab
warmupPollTimeout: 10s
resourceStatusPollTimeout: 60m
keyLoaderPollTimeout: 20m
adminKey: BDCC-DSS-POC
edgeImage: docker.epmc-bdcc.projects.epam.com/dlab-aws-edge
fileLengthCheckDelay: 500ms

notebookImage: docker.epmc-bdcc.projects.epam.com/dlab-aws-jupyter

emrImage: docker.epmc-bdcc.projects.epam.com/dlab-aws-emr
emrEC2RoleDefault: EMR_EC2_DefaultRole
emrServiceRoleDefault: EMR_DefaultRole

processMaxThreadsPerJvm: 50
processMaxThreadsPerUser: 5
processTimeout: 180m

selfService:
  protocol: http
  host: localhost
  port: 8080
  jerseyClient:
    timeout: 3s
    connectionTimeout: 3s

securityService:
  protocol: http
  host: localhost
  port: 8090
  jerseyClient:
    timeout: 10s
    connectionTimeout: 10s

server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /tmp/dlab/log/request-provisioning.log
        archivedLogFilenamePattern: /tmp/dlab/log/request-provisioning-%d.log
  applicationConnectors:
    - type: http
      port: 8084
  adminConnectors:
    - type: http
      port: 8085

logging:
  level: INFO
  loggers:
    com.epam: DEBUG
    com.aegisql: DEBUG
  appenders:
#    - type: console
    - type: file
      currentLogFilename: /tmp/dlab/log/provisioning.log
      archivedLogFilenamePattern: /tmp/dlab/log/provisioning-%d.log