responseDirectory: /tmp/dlab
warmupPollTimeout: 10s
keyLoaderPollTimeout: 5m

self-service:
  protocol: http
  host: EPRUPETW1232.PETERSBURG.epam.com
  port: 8080
  jerseyClient:
    timeout: 3s
    connectionTimeout: 3s

server:
  applicationConnectors:
    - type: http
      port: 8084
  adminConnectors:
    - type: http
      port: 8085

logging:
  level: INFO
  loggers:
    com.epam: DEBUG
  appenders:
    - type: console