#Copyright 2016 EPAM Systems, Inc.
# 
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
#
#defaultRedirectFromAuthentication: http://localhost:8080/best
#inactiveUserTimeoutMillSec: 3600000
ldapConnectionConfig:
  ldapHost: localhost
  ldapPort: 3890
  name: cn=admin,dc=example,dc=com
  credentials: ldap
ldapBindTemplate: uid=%s,ou=People,dc=example,dc=com
ldapSearch: 
  - scope: SUBTREE
    attributes: 
      - cn
    timeLimit: 0
    base: dc=example,dc=com
    filter: "(&(objectClass=inetOrgPerson)(uid=${username}))"
    searchResultProcessor:
      language: python
      code: |
        def enrichUserInfo(ui,context):
          print ui['username']
          ui['firstName'] = 'John'
          ui['lastName'] = 'Doe'
          print context
          return ui
    #and more
      
#openLdapConfig: 
#  host: ec2-52-33-6-197.us-west-2.compute.amazonaws.com
#  port: 389
#  base: dc=example,dc=com
#  username: admin
#  password: ldap
server:
  applicationConnectors:
  - type: http
    port: 8090
  adminConnectors:
  - type: http
    port: 8091  
logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    com.epam: DEBUG
  appenders:
    - type: console