server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

mongo:
  host: localhost
  port: 27017
  database: dlab

security-service:
  protocol: http
  host: localhost
  port: 8082