server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

mongo:
  host:
  port:
  username:
  password:

security-service:
  protocol: http
  host: localhost
  port: 8082